### ISSUE TITLE
UI: bottom navigation rounded border fix

### ISSUE THREAD

**Issue by 4seer** [4seer/openflutterecommerceapp#107]
The rounded border should be added to the bottom navigation
http://prntscr.com/rmb8gr

**Comment by Yahhi** [comment]
I want to mention that in design it has elevation or shadow. It makes it more visible when background is white. I think it is required to implement it too

**Comment by 4seer** [comment]
List of widgets is described here https://medium.com/@openflutterproject/open-flutter-project-e-commerce-app-flutter-widgets-f63f3c33ac94

**Comment by ptyagicodecamp** [comment]
PR: https://github.com/4seer/openflutterecommerceapp/pull/114
