### ISSUE TITLE
UI when tablets or phones are in horizontal position

### ISSUE THREAD

**Issue by Yahhi** [4seer/openflutterecommerceapp#108]
When the devices are in horizontal position the UI on the main page seems to be strange. It is required to lock rotation when the app is active or to create a more appropriate layout for a horizontal view.
![image](https://user-images.githubusercontent.com/4613133/77634814-a1c8f000-6f62-11ea-96e9-fec464bcdf14.png)

**Comment by ptyagicodecamp** [comment]
Submitted PR: https://github.com/4seer/openflutterecommerceapp/pull/114
