### ISSUE TITLE
facing this error 'The getter 'length' was called on null.'

### ISSUE THREAD

**Issue by SriRamGovardhanam** [4seer/openflutterecommerceapp#128]
Hello
I am new to flutter
while running the project i am getting this error
```The following NoSuchMethodError was thrown building BlocBuilder<CategoryBloc, CategoryState>(dirty, state: _BlocBuilderBaseState<CategoryBloc, CategoryState>#6d0cc):
The getter 'length' was called on null.
Receiver: null
Tried calling: length

The relevant error-causing widget was: 
  BlocBuilder<CategoryBloc, CategoryState> file:///E:/openflutterecommerceapp-master/lib/presentation/features/categories/views/list_view.dart:42:13
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _CategoriesListViewState.buildCategoryList (package:openflutterecommerce/presentation/features/categories/views/list_view.dart:77:36)
#2      _CategoriesListViewState.build.<anonymous closure> (package:openflutterecommerce/presentation/features/categories/views/list_view.dart:63:27)
#3      BlocBuilder.build (package:flutter_bloc/src/bloc_builder.dart:90:57)
#4      _BlocBuilderBaseState.build (package:flutter_bloc/src/bloc_builder.dart:162:48)
```

please someone help me out

**Comment by maluduena** [comment]
This project is abandoned? Yesterday I downloaded the latest version and it throws that same error in addition to the expired certificate.

**Comment by 4seer** [comment]
Hello. The project is not abandoned. I will take a look at the issue this week.

**Comment by 4seer** [comment]
> 
> 
> Hello
> I am new to flutter
> while running the project i am getting this error
> 
> ```
> The getter 'length' was called on null.
> Receiver: null
> Tried calling: length
> 
> The relevant error-causing widget was: 
>   BlocBuilder<CategoryBloc, CategoryState> file:///E:/openflutterecommerceapp-master/lib/presentation/features/categories/views/list_view.dart:42:13
> When the exception was thrown, this was the stack: 
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
> #1      _CategoriesListViewState.buildCategoryList (package:openflutterecommerce/presentation/features/categories/views/list_view.dart:77:36)
> #2      _CategoriesListViewState.build.<anonymous closure> (package:openflutterecommerce/presentation/features/categories/views/list_view.dart:63:27)
> #3      BlocBuilder.build (package:flutter_bloc/src/bloc_builder.dart:90:57)
> #4      _BlocBuilderBaseState.build (package:flutter_bloc/src/bloc_builder.dart:162:48)
> ```
> 
> please someone help me out

Get new updates after latest pull request from the master branch.
Check that your device is connected to the internet.
