### ISSUE TITLE
Hyperlocal Marketplace Feature support

### ISSUE THREAD

**Issue by birender-s** [4seer/openflutterecommerceapp#131]
Hi Team, just wanted to check possibility to support Hyperlocal Marketplace wherein seller can post Ads for products (type, quantity, price, location...) from within App, choose distance for service location. If it's already considered or any pointers on what can be done to support it (from app and backend integration perspective), it will be much appreciated. Thanks !

**Comment by oliverboamah** [comment]
This is an important feature for businesses in a bid to attract more customers by running Ads/Promotions. It's a win-win situation for both the seller and the buyer, and it will make the app Hyperlocal Marketplace centric too. 

A table can be reserved for storing Ads in the backend, and the user can choose the service location by clicking on a location via a Google maps integration when creating the Ad. Here's a great plugin for Google map integration: https://pub.dev/packages/google_maps_flutter

**Comment by birender-s** [comment]
Thanks @codingoliver for your positive feedback!
Can this feature be added in the app roadmap and prioritized? Thanks once again

**Comment by 4seer** [comment]
Reopen the issue if still needed.
