### ISSUE TITLE
Can't add to Cart

### ISSUE THREAD

**Issue by linxkaa** [4seer/openflutterecommerceapp#133]
I get this issues when i clone the latest version on this repo, any help?
![image](https://user-images.githubusercontent.com/57997512/91422781-d29ab180-e881-11ea-8e21-15dfef9284c6.png)

**Comment by 4seer** [comment]
I will check it over the weekend.

**Comment by KumarGanesanIBM** [comment]
@linxkaa 
is it happening when you try to add an item which is there in favourite?

**Comment by linxkaa** [comment]
Yeah it was on favorite, i also couldnt register in the app

**Comment by Mastersam07** [comment]
I am facing this exact issue. Add to cart returns the error shown in the shot provided by @linxkaa . It is not particular to adding the item to cart when it already is in favourite. All instances of adding to cart return that error.

@linxkaa did you fix or find a way around?

**Comment by 4seer** [comment]
> 
> 
> I am facing this exact issue. Add to cart returns the error shown in the shot provided by @linxkaa . It is not particular to adding the item to cart when it already is in favourite. All instances of adding to cart return that error.
> 
> @linxkaa did you fix or find a way around?

Can you add here debug trace?

**Comment by 4seer** [comment]
Should work now.
