### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by JuanmaMenendez** [4seer/openflutterecommerceapp#134]
Please add some instructions about what is need it and the steps to run this project (eg: create a WooComerce website, run X command, etc..)

**Comment by ajatsoft** [comment]
how to add   //?consumer_key=ck_*****&consumer_secret=cs_**** goes here


where I can add my keys?

**Comment by ajatsoft** [comment]
> how to add //?consumer_key=ck_*****&consumer_secret=cs_**** goes here
> 
> where I can add my keys?

solution:
  static const _woocommerceKeys = '?consumer_key=ck_*****&consumer_secret=cs_****';




here you have an error:

 static String get productCategories => serverAddress  +_categorySuffix + _woocommerceKeys;
    // (useStatic ? _productCategoriesCached
    //   : serverAddress  +_categorySuffix + _woocommerceKeys);

  static String get products => serverAddress  +_productSuffix + _woocommerceKeys;
    // (useStatic ? _productsCached
    //   : serverAddress  +_productSuffix + _woocommerceKeys);

  static String get promos => serverAddress  +_promoSuffix + _woocommerceKeys;
//     (useStatic ? _promosCached
//       : serverAddress  +_promoSuffix + _woocommerceKeys);


duplicate  ==> serverAddress string

**Comment by 4seer** [comment]
It should connect to our current test woocommerce domain and show products. If you still have issues reopen this issue.
