### ISSUE TITLE
Want to provide a dedicated backend for the application. Moving on from managed server.

### ISSUE THREAD

**Issue by vorishirne** [4seer/openflutterecommerceapp#144]
Hy, I am about to write the entire backend, with Kubernetes, docker, golang and postgresql/greenplum. 
Need collaboration on to this from the UI people. I would anyways be creating it, but would be off a lot of help if someone from UI team can help collaborate. I am not that experienced in UI but I will manage if no one comes.

**Comment by vorishirne** [comment]
@4seer if u see, It's a hurdle to take the app to production with some 3rd party api as backend. It is not extensible.

**Comment by HenryMaliseli** [comment]
Hello..!! Am Henry..

**Comment by vorishirne** [comment]
Hy Henry

**Comment by HenryMaliseli** [comment]
Hi, I am interested with your project, I would like to know more about this project, am little bit good in UI design, I think we can share.

**Comment by vorishirne** [comment]
Hy yo, so my mail is vorishirne@gmail.com. Can we discuss our bandwidths and mutual goals sometime.

**Comment by 4seer** [comment]
> @4seer if u see, It's a hurdle to take the app to production with some 3rd party api as backend. It is not extensible.

Sure we can discuss it. Do you have something specific in mind when you talk about backend? An open source project may be?

**Comment by vorishirne** [comment]
You got it. I am onto an Open source complete backend for this E-commerce app. How can we discuss.

**Comment by vorishirne** [comment]
The apis I can create pretty fast, as that has been my usual day to day work.

**Comment by 4seer** [comment]
Lets discuss it here so others can take part too.

**Comment by tilak-gm** [comment]
@4seer @vorishirne Count me in, for the backend dev work.

**Comment by vorishirne** [comment]
@4seer I saw this comment https://github.com/4seer/openflutterecommerceapp/issues/55#issuecomment-593103668

Which states that APIs written by ourselves can be added seperately. Can you explain me how difficult it would be to shift slowly-slowly, may be in course of 4 months to a different backend. How the development will be aligned with the master? Do you even believe that it would be a long term win to have a custom backend, that can server data, fields and apply any operation as per the desire without compromises?

**Comment by vorishirne** [comment]
Thanks @tilak-gm . I hope you are fine with Golang and Kubernetes.

**Comment by 4seer** [comment]
You are talking about tech project without details. It is hard to give you a concrete answer on how difficult it will be do something without tech specs.
I propose you to start doing something with the project on custom backend and once there will be specifics on the API and what it will take to integrate it we can discuss it.

**Comment by vorishirne** [comment]
Ok, can u specify what tech-specs exactly you are aiming for. Also, let me start with understanding the application in place. There is good amount of documentation there.

**Comment by HenrySode** [comment]
ok
