### ISSUE TITLE
textTheme.headline* not found.. 

### ISSUE THREAD

**Issue by rdurelli** [4seer/openflutterecommerceapp#46]
textTheme.headline* not found.. 

Which Flutter version should be used?

Thanks in advance.

**Comment by 4seer** [comment]
master or dev.
See details here https://medium.com/@openflutterproject/open-flutter-project-developer-guidelines-4a4fa3fa289e

```
flutter channel master
flutter upgrade
```

or 

```
flutter channel dev
flutter upgrade
```
