### ISSUE TITLE
Server API discussion

### ISSUE THREAD

**Issue by 4seer** [4seer/openflutterecommerceapp#55]
Provide your propositions on the server API we should use.

Our current vision is to pick up one of the open source e-commerce platforms available there:

1. [WooCommerce](https://woocommerce.com/) 
2. [Magento Community](https://magento.com/)
3. [Presta Shop](https://www.prestashop.com/)

Join discussion to identify the best platform to start with.

**Comment by Yahhi** [comment]
I visited API doc pages of these sites and found that  PrestaShop wants developers to define API by themselves. This option seems to be too difficult in our case IMHO. So I am against Presta Shop.
I like WooCommerce documentation form. It is clear and easy to use and understand. https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction
So as for me, I would prefer WooCommerce

**Comment by Yahhi** [comment]
Additionally, I want to mention that we can start with one of these projects, but then can add others (even written by ourselves)

**Comment by 4seer** [comment]
Besides that WooCommerce seems to have one of the biggest communities. And, yes, having a clear documented API is a big advantage.

**Comment by umair13adil** [comment]
I have read this [blog](https://medium.com/@floship/prestashop-vs-magento-vs-woocommerce-vs-shopify-comparison-2e59c4b225d1) which provides a comparison between these platforms and i also checked the APIs and its documentation, I too think WooCommerce will be an excellent choice.

**Comment by rkBoahene** [comment]
WooCommerce has a comprehensive api documentation compared to magento, so i'd suggest we go with that.

**Comment by 4seer** [comment]
So let`s proceed with WooCommerce.
