### ISSUE TITLE
Functional Requirement Document creation

### ISSUE THREAD

**Issue by 4seer** [4seer/openflutterecommerceapp#68]
We are moving to more detailed functionality implementation. Therefore it is good time to create a more detailed document on that. The goal of the document is creation of a detailed specification on application business logic and data access layer.  I propose the following structure as a start.

1. Flutter Clean Architecture Layers
1.1. Domain
1.2. App
1.3. Data
1.4. Device

2. Feature Implementation and use case description
2.1. Home/Splash Screens
2.2. Product categories and products
2.3. Cart and Checkout
2.4. User Accounts
2.5. Promotion

Add your thoughts on what we should include to make the tasks clear enough to share within the team.

**Comment by umair13adil** [comment]
If we can add a flow diagram of **Application Layer** in this document like the one that is in this [blog](https://medium.com/@rodrigolmti/clean-architecture-no-flutter-1888c4baa6bc), then it would be very helpful in visually understanding the layers and purpose of each layer of the app.

**Comment by 4seer** [comment]
I was thinking about a more detailed explanation of use cases. The functional requirement document description is [here](https://www.guru99.com/functional-requirement-specification-example.html).
It is a very detailed document usually. I do not think we need to make it that deep. But what we can do is a description of use-cases the way we see it so by the time we start the actual development we have a clear understanding of how it should be. It is a common practice and helps get the tasks done with fewer iterations.

The detailed explanation of functionality implementation may include the UML diagrams like [this one](https://www.controleng.com/wp-content/uploads/sites/2/2012/02/ctl1203it-a3-UML-SD-interaction-Slider.jpg).

Since we have WooCommerce API described we know what is on the backend and we have UI that shows us what a user can click we can make a high-level overview of the list of all use cases and what should happen. That will represent the task list for implementation that each on of us can take. If we find a missing use case we just add it and add the task itself as an issue on Github.

To make a long story short, I think we can start with a complete list of use-cases we want to implement so everybody can add a description and vision of what should happen within that use-case. The use cases will be group by features (products, product rating, cart, etc).

**Comment by 4seer** [comment]
https://medium.com/@openflutterproject/open-flutter-project-e-commerce-app-use-cases-and-features-6b7414a6e708 use-case description for the app.
