### ISSUE TITLE
My favourites UI

### ISSUE THREAD

**Issue by 4seer** [4seer/openflutterecommerceapp#9]
My favourites UI
![](https://miro.medium.com/max/1478/1*seI6wzCq1vGUdgpIFvb4BA.png)

**Comment by umair13adil** [comment]
@4seer Favourites' UI header will need a collapsing toolbar with a search feature, should I embed it within 'OpenFlutterScaffold' class or keep it separate?

**Comment by 4seer** [comment]
> 
> 
> @4seer Favourites' UI header will need a collapsing toolbar with a search feature, should I embed it within 'OpenFlutterScaffold' class or keep it separate?

Yes

**Comment by umair13adil** [comment]
You are saying yes to keeping it separate?

**Comment by 4seer** [comment]
> 
> 
> You are saying yes to keeping it separate?

Let`s keep it separate first and then we will see how we will reuse it in the future.
