### ISSUE TITLE
Add fonts to the App

### ISSUE THREAD

**Issue by 4seer** [4seer/openflutterecommerceapp#96]
We need to add fonts to the app.
Font used in design: Metropolis

Possible solution: https://pub.dev/packages/google_fonts

**Comment by Mastersam07** [comment]
Can I pick up this issue?

**Comment by 4seer** [comment]
> 
> 
> Can I pick up this issue?

You can always propose your solution with a pull request into development branch.

**Comment by Mastersam07** [comment]
Okay the

> > Can I pick up this issue?
> 
> You can always propose your solution with a pull request into development branch.

Okay then

**Comment by 4seer** [comment]
Fonts do not look like in design after adding font. Font style "Metropolis-black" should be added for titles and other. Compare what is in the app and how it should be in design https://medium.com/@openflutterproject/open-flutter-project-e-commerce-app-fe97570a633

**Comment by umair13adil** [comment]
Yes, I noticed that too. The fonts on each screen need to be adjusted, I will do that, I was waiting for this commit to be reviewed.

**Comment by 4seer** [comment]
We just need to add appropriate fontWeight so it will be used according to the design.

**Comment by umair13adil** [comment]
Okay, I will make sure of that.

**Comment by 4seer** [comment]
Here is a an example https://github.com/4seer/openflutterecommerceapp/commit/d2747349e2a6a84b99ba6ed7f7342246e6cdb60b

**Comment by 4seer** [comment]
> Okay, I will make sure of that.

Hello Umair! Did you finish all updates within this task?

**Comment by Anikets08** [comment]
hey is the issue solved ??

**Comment by RasheeqZaman** [comment]
Hi, I was looking forward to making some contribution to this project. Is this issue resolved already?

**Comment by 4seer** [comment]
> Hi, I was looking forward to making some contribution to this project. Is this issue resolved already?

Umair did his part. There are some lint warning left. You proceed with your contribution. Make a pull request and we will review it.
