### ISSUE TITLE
Cant Import APP

### ISSUE THREAD

**Issue by mancera2** [4seer/openflutterecommerceapp#99]
error - The named parameter 'headline1' isn't defined - lib\config\theme.dart:56:9 - undefined_named_parameter
  error - The getter 'headline1' isn't defined for the class 'TextTheme' - lib\config\theme.dart:56:36 - undefined_getter
  error - The named parameter 'headline2' isn't defined - lib\config\theme.dart:58:9 - undefined_named_parameter
  error - The getter 'headline2' isn't defined for the class 'TextTheme' - lib\config\theme.dart:58:36 - undefined_getter
  error - The named parameter 'headline3' isn't defined - lib\config\theme.dart:62:9 - undefined_named_parameter
  error - The getter 'headline3' isn't defined for the class 'TextTheme' - lib\config\theme.dart:62:36 - undefined_getter
  error - The named parameter 'headline4' isn't defined - lib\config\theme.dart:65:9 - undefined_named_parameter
  error - The getter 'headline4' isn't defined for the class 'TextTheme' - lib\config\theme.dart:65:36 - undefined_getter
  error - The named parameter 'headline5' isn't defined - lib\config\theme.dart:67:9 - undefined_named_parameter
  error - The getter 'headline5' isn't defined for the class 'TextTheme' - lib\config\theme.dart:67:36 - undefined_getter
  error - The named parameter 'headline6' isn't defined - lib\config\theme.dart:69:9 - undefined_named_parameter
  error - The getter 'headline6' isn't defined for the class 'TextTheme' - lib\config\theme.dart:69:36 - undefined_getter
  error - The named parameter 'subtitle1' isn't defined - lib\config\theme.dart:71:9 - undefined_named_parameter
  error - The getter 'headline1' isn't defined for the class 'TextTheme' - lib\config\theme.dart:71:36 - undefined_getter
  error - The named parameter 'subtitle2' isn't defined - lib\config\theme.dart:73:9 - undefined_named_parameter
  error - The getter 'headline1' isn't defined for the class 'TextTheme' - lib\config\theme.dart:73:36 - undefined_getter
  error - The named parameter 'bodyText1' isn't defined - lib\config\theme.dart:84:9 - undefined_named_parameter
  error - The getter 'bodyText1' isn't defined for the class 'TextTheme' - lib\config\theme.dart:84:36 - undefined_getter
  error - The named parameter 'bodyText2' isn't defined - lib\config\theme.dart:89:9 - undefined_named_parameter
  error - The getter 'bodyText2' isn't defined for the class 'TextTheme' - lib\config\theme.dart:89:36 - undefined_getter

**Comment by Yahhi** [comment]
Please, use flutter beta. Seems like you are on stable version. It is mentioned in the readme.md

**Comment by Mastersam07** [comment]
Please switch to the beta or dev channel.

flutter channel beta
flutter upgrade

**Comment by mancera2** [comment]
thank you solved
